version: '3.8'
services:
  kino:
    container_name: kino
    restart: always
    image: ghcr.io/wubanga/kino:${IMAGE_VERSION}
    ports:
      - 5000:5000
    labels: 
      - traefik.http.routers.kino.rule=Host(`kino.okinazuno.me`)
      - traefik.http.routers.kino.tls=true
      - traefik.http.routers.kino.tls.certresolver=letsEncrypt
      - traefik.http.services.kino.loadbalancer.server.port=5000
      
networks:
  default:
    external: true
    name: traefik-network