version: '3.8'
services:
  s3mer:
    container_name: kino
    restart: always
    image: ghcr.io/wubanga/kino:${IMAGE_VERSION}
    ports:
      - 5000:5000
    labels: 
      - traefik.http.routers.s3mer.rule=Host(`kino.okinazuno.me`)
      - traefik.http.routers.s3mer.tls=true
      - traefik.http.routers.s3mer.tls.certresolver=letsEncrypt
networks:
  default:
    external: true
    name: traefik-network